# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretProviderClass:
  name: kubernetes.secretproviderclass.keyvault
  keyVaultName: 
  resourceGroup: 
  subscriptionId: 
  tenantId: 
  databaseConnectionString: 
  databasePrimaryKey: 
  serviceBusConnectionString: 
  storageConnectionString: 