apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.azureIdentityBinding.name }}
spec:
  azureIdentity: "{{ .Values.azureIdentityBinding.azureIdentity }}"
  selector: "{{ .Values.azureIdentityBinding.selector }}"