apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.dapr.stateConsumerState.name }}
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: "{{ .Values.dapr.stateConsumerState.url }}"
  - name: masterKey
    secretKeyRef:
      name: {{ .Values.dapr.stateConsumerState.masterKey }}
      key: {{ .Values.dapr.stateConsumerState.masterKey }}
  - name: database
    value: "{{ .Values.dapr.stateConsumerState.database }}"
  - name: collection
    value: "workflow1-consumer"
scopes:
  - consumer-api
auth:
  secretStore: {{ .Values.dapr.secretStore.name }}