# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

azureIdentity:
  name: kubernetes.azureidentity
  resourceID: 
  clientID: 
azureIdentityBinding:
  name: kubernetes.azureidentitybinding
  azureIdentity: kubernetes.azureidentity
  selector: kubernetes.azureidentity