# Default values for retropos-system-dapr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dapr:
  secretStore:
    name: dapr.secretstore
    vaultName:
    clientId:
  bindingInternalQueue:
    name: dapr.binding.internal-queue
    connectionString:
    queueName: internal-queue
  stateConsumerState:
    name: dapr.state.consumer-state
    url:
    masterKey:
    database:
  tracing:
    name: dapr.tracing
  exporter:
    name: dapr.exporter
