# Default values for retropos-system.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secretProviderClass:
  name: kubernetes.secretproviderclass.keyvault
  keyvaultName: 
  resourceGroup: 
  subscriptionId: 
  tenantId: 
  databaseConnectionString: 
  databasePrimaryKey: 
  serviceBusConnectionString: 
  storageConnectionString: 

durableAPI:
  deployment:
    replicas: 4
    aadpodidbinding: kubernetes.azureidentity
    name: durable-orchestration-api
    containerName: durable-orchestration-api
    image:
      repository: 
      pullPolicy: Always 
    env:
      azureWebJobsStorage: 
      durableBindingComponentName: dapr.binding.durable-registration
      maxWorkloads: 1
      maxRequestsPerWorkload: 500
  service:
    name: durable-orchestration-api
    type: LoadBalancer

consumerAPI:
  deployment:
    replicas: 1
    aadpodidbinding: kubernetes.azureidentity
    name: consumer-api
    containerName: consumer-api
    image:
      repository: 
      pullPolicy: Always 
    env:
      azureWebJobsStorage: 
      serviceBusConnectionString: 
      consumerStateComponentName: dapr.state.consumer-state
  keda:
    triggerAuthentication:
      name: keda.triggerauthentication.consumer-api
    scaledObject:
      name: keda.scaledobject.consumer-api
      deploymentName: consumer-api
      pollingInterval: 5
      coolDownPeriod: 0
      minReplicaCount: 10
      maxReplicaCount: 50
      triggers:
        type: azure-servicebus
        queueName: durable-registration
        messageCount: 5
        authenticationRef: keda.triggerauthentication.consumer-api