apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: retropos.warehouse.state
  namespace: default
spec:
  type: state.azure.cosmosdb
  metadata:
  - name: url
    value: https://retroposcos01.documents.azure.com:443/
  - name: masterKey
    secretKeyRef:
      name: retropos-warehouse-state
      key: retropos-warehouse-state
  - name: database
    value: retropos
  - name: collection
    value: warehouse
scopes:
  - warehouse-service
auth:
  secretStore: retropos.security.secret