apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: retropos.security.secret
  namespace: default
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: retroposkv01
  - name: spnTenantId
    value: "[hidden]"
  - name: spnClientId
    value: "[hidden]"
  - name: spnCertificateFile
    value : "[hidden]"
scopes:
  - warehouse-service
  - audit-service
  - durable-service