apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: retropos.audit.binding
  namespace: default
spec:
  type: bindings.azure.blobstorage
  metadata:
  - name: storageAccount
    value: retroposstg01
  - name: storageAccessKey
    secretKeyRef:
      name: retropos-audit-binding
      key: retropos-audit-binding
  - name: container
    value: audit
scopes:
  - audit-service
auth:
  secretStore: retropos.security.secret