apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: retropos.security.secret
  namespace: default
spec:
  type: secretstores.azure.keyvault
  metadata:
  - name: vaultName
    value: [REPLACE]
  - name: spnTenantId
    value: [REPLACE]
  - name: spnClientId
    value: [REPLACE]
  - name: spnCertificateFile
    value : [REPLACE]
scopes:
  - warehouse-service
  - audit-service