apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: retropos.product-registration.pubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  metadata:
  - name: connectionString
    secretKeyRef:
      name: [REPLACE]
      key: [REPLACE]
scopes:
  - warehouse-service
  - audit-service
auth:
  secretStore: retropos.security.secret